/*
    deepscan-auto-hack.script
    for bitburner version: 0.35.1

    winners don't use copyright
    last version of this script should be at https://github.com/desci/netscripts.d

    This script automatically hacks every hackable server in the network.
    It will not attempt to root servers.

*/

origin = getHostname();
ownNodes = [ "home", origin ];
hackedNodesToday = [];

while (true) {
    foundnodes = [];
    stack = [];
    stack.push(origin);
    while(stack.length > 0) {
        node = stack.pop();
        if (! foundnodes.includes(node)) {
            tprint("----------------------------------------");
            tprint("Working on " + node + "...");
            
            // We will only hack the server if the necessary conditions are met
            if (! ownNodes.includes(node)) {
                if (hasRootAccess(node)) {
                    tprint("Sending hack files to " + node + "...");
                    if (scp("remote-hack.script", "home", node)) {
                        tprint("Scripts sent to " + node + ", attempting to execute it...");
                        if (isRunning("remote-hack.script", node) || exec("remote-hack.script", node)) {
                            tprint(node + " successfully hacked!");
                            if (! hackedNodesToday.includes(node)) hackedNodesToday.push(node);
                        } else {
                            tprint("Scripts failed to execute at " + node);
                        }
                    } else {
                        tprint("Failed uploading scripts to " + node);
                    }
            } else {
                tprint(node + " won't be hacked today because we don't have root access");
            }
            } else {
                tprint(node + " won't be hacked today because it is included in ownNodes");
            }
            
            tprint("adding " + node + " to foundnodes...");
            foundnodes.push(node);
            tprint("scanning " + node + "...");
            nextNodes = scan(node);
            for (i = 0; i < nextNodes.length; ++i) {
                stack.push(nextNodes[i]);
            }
            tprint("current hacking stack: " + stack);
        }
    }
    tprint("========================================");
    tprint("Hacked servers so far: " + hackedNodesToday.length);
}

