/*
    deepscan-auto-hack.script
    for bitburner version: 0.35.1

    winners don't use copyright
    last version of this script should be at https://github.com/desci/netscripts.d

    This script automatically hacks every hackable server in the network.
    It will not attempt to root servers.

*/

origin = getHostname();

ownNodes = [ "home", origin ];
rootedNodesToday = 0;

while (true) {
    foundnodes = [];
    stack = [];
    stack.push(origin);
    while(stack.length > 0) {
        node = stack.pop();
        if (! foundnodes.includes(node)) {
            tprint("----------------------------------------");
            tprint("Working on " + node + "...");
            
            // We will only hack the server if the necessary conditions are met
            if (! ownNodes.includes(node) && hasRootAccess(node)) {
                tprint("Hacking " + node + "...");
                //TODO change to switch case when netscript supports it
                hack(node);
                grow(node);
                grow(node);
                weaken(node);
                weaken(node);
                weaken(node);
                weaken(node);
                rootedNodesToday++;
            } else {
                tprint(node + " can't or won't be hacked today");
            }
            
            foundnodes.push(node);
            nextNodes = scan(node);
            for (i = 0; i < nextNodes.length; ++i) {
                stack.push(nextNodes[i]);
            }
        }
    }
    tprint("========================================");
    tprint("Hacked servers so far: " + rootedNodesToday);
}

